datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test
  username:
  password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true











## Database connection settings
#spring.datasource.url=jdbc:mysql://localhost:3306/feel_app
#spring.datasource.username=feel_app
#spring.datasource.password=l!ft0ffProject
#
## Specify the DBMS
#spring.jpa.database = MYSQL
#
## Show or not log for each sql query
#spring.jpa.show-sql = false
#
## Hibernate ddl auto (create, create-drop, update)
#spring.jpa.hibernate.ddl-auto = update
#
## Use spring.jpa.properties.* for Hibernate native properties (the prefix is
## stripped before adding them to the entity manager)
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
